//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.Logite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.Logite.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string CaptionView {
            get {
                return ResourceManager.GetString("CaptionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string FilterDays001 {
            get {
                return ResourceManager.GetString("FilterDays001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 days.
        /// </summary>
        public static string FilterDays002 {
            get {
                return ResourceManager.GetString("FilterDays002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 days.
        /// </summary>
        public static string FilterDays003 {
            get {
                return ResourceManager.GetString("FilterDays003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days.
        /// </summary>
        public static string FilterDays007 {
            get {
                return ResourceManager.GetString("FilterDays007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 days.
        /// </summary>
        public static string FilterDays014 {
            get {
                return ResourceManager.GetString("FilterDays014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 days.
        /// </summary>
        public static string FilterDays030 {
            get {
                return ResourceManager.GetString("FilterDays030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 days.
        /// </summary>
        public static string FilterDays060 {
            get {
                return ResourceManager.GetString("FilterDays060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90 days.
        /// </summary>
        public static string FilterDays090 {
            get {
                return ResourceManager.GetString("FilterDays090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120 days.
        /// </summary>
        public static string FilterDays120 {
            get {
                return ResourceManager.GetString("FilterDays120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180 days.
        /// </summary>
        public static string FilterDays180 {
            get {
                return ResourceManager.GetString("FilterDays180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One year.
        /// </summary>
        public static string FilterYears1 {
            get {
                return ResourceManager.GetString("FilterYears1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two years.
        /// </summary>
        public static string FilterYears2 {
            get {
                return ResourceManager.GetString("FilterYears2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three years.
        /// </summary>
        public static string FilterYears3 {
            get {
                return ResourceManager.GetString("FilterYears3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four years.
        /// </summary>
        public static string FilterYears4 {
            get {
                return ResourceManager.GetString("FilterYears4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string HeaderDomain {
            get {
                return ResourceManager.GetString("HeaderDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        public static string HeaderDomainView {
            get {
                return ResourceManager.GetString("HeaderDomainView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string HeaderStartView {
            get {
                return ResourceManager.GetString("HeaderStartView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Detail.
        /// </summary>
        public static string HeaderTableDetail {
            get {
                return ResourceManager.GetString("HeaderTableDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string HeaderTableView {
            get {
                return ResourceManager.GetString("HeaderTableView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Logite.
        /// </summary>
        public static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string MenuItemAddDomain {
            get {
                return ResourceManager.GetString("MenuItemAddDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear data.
        /// </summary>
        public static string MenuItemClearData {
            get {
                return ResourceManager.GetString("MenuItemClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string MenuItemDomainCharts {
            get {
                return ResourceManager.GetString("MenuItemDomainCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string MenuItemDomainOverview {
            get {
                return ResourceManager.GetString("MenuItemDomainOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string MenuItemDownload {
            get {
                return ResourceManager.GetString("MenuItemDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuItemFile {
            get {
                return ResourceManager.GetString("MenuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuItemHelp {
            get {
                return ResourceManager.GetString("MenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string MenuItemImport {
            get {
                return ResourceManager.GetString("MenuItemImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string MenuItemRemoveDomain {
            get {
                return ResourceManager.GetString("MenuItemRemoveDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset window.
        /// </summary>
        public static string MenuItemResetWindow {
            get {
                return ResourceManager.GetString("MenuItemResetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuItemSave {
            get {
                return ResourceManager.GetString("MenuItemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuItemSettings {
            get {
                return ResourceManager.GetString("MenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started.
        /// </summary>
        public static string MenuItemStart {
            get {
                return ResourceManager.GetString("MenuItemStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table info.
        /// </summary>
        public static string MenuItemTableInfo {
            get {
                return ResourceManager.GetString("MenuItemTableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MenuItemTools {
            get {
                return ResourceManager.GetString("MenuItemTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        public static string NavHeaderDomain {
            get {
                return ResourceManager.GetString("NavHeaderDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string NavHeaderSetup {
            get {
                return ResourceManager.GetString("NavHeaderSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string NavHeaderTools {
            get {
                return ResourceManager.GetString("NavHeaderTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will add a new domain entry with default values. Once added, you can edit the values..
        /// </summary>
        public static string TextAddDomain {
            get {
                return ResourceManager.GetString("TextAddDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ftp.
        /// </summary>
        public static string TextFtp {
            get {
                return ResourceManager.GetString("TextFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string TextFtpHost {
            get {
                return ResourceManager.GetString("TextFtpHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key file.
        /// </summary>
        public static string TextFtpKeyFile {
            get {
                return ResourceManager.GetString("TextFtpKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local log directory.
        /// </summary>
        public static string TextFtpLocalDirectory {
            get {
                return ResourceManager.GetString("TextFtpLocalDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing files.
        /// </summary>
        public static string TextFtpOverwrite {
            get {
                return ResourceManager.GetString("TextFtpOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression.
        /// </summary>
        public static string TextFtpRegex {
            get {
                return ResourceManager.GetString("TextFtpRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote log directory.
        /// </summary>
        public static string TextFtpRemoteDirectory {
            get {
                return ResourceManager.GetString("TextFtpRemoteDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string TextFtpUser {
            get {
                return ResourceManager.GetString("TextFtpUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the size and position of the main window.
        /// </summary>
        public static string ToolTipResetMainWindow {
            get {
                return ResourceManager.GetString("ToolTipResetMainWindow", resourceCulture);
            }
        }
    }
}
