//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.Logite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.Logite.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string HeaderDomain {
            get {
                return ResourceManager.GetString("HeaderDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        public static string HeaderDomainView {
            get {
                return ResourceManager.GetString("HeaderDomainView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string HeaderStartView {
            get {
                return ResourceManager.GetString("HeaderStartView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Detail.
        /// </summary>
        public static string HeaderTableDetail {
            get {
                return ResourceManager.GetString("HeaderTableDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string HeaderTableView {
            get {
                return ResourceManager.GetString("HeaderTableView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Logite.
        /// </summary>
        public static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string MenuItemAddDomain {
            get {
                return ResourceManager.GetString("MenuItemAddDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application options.
        /// </summary>
        public static string MenuItemAppOptions {
            get {
                return ResourceManager.GetString("MenuItemAppOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear data.
        /// </summary>
        public static string MenuItemClearData {
            get {
                return ResourceManager.GetString("MenuItemClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string MenuItemDomainCharts {
            get {
                return ResourceManager.GetString("MenuItemDomainCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string MenuItemDomainOverview {
            get {
                return ResourceManager.GetString("MenuItemDomainOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuItemFile {
            get {
                return ResourceManager.GetString("MenuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuItemHelp {
            get {
                return ResourceManager.GetString("MenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string MenuItemImport {
            get {
                return ResourceManager.GetString("MenuItemImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string MenuItemRemoveDomain {
            get {
                return ResourceManager.GetString("MenuItemRemoveDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset window.
        /// </summary>
        public static string MenuItemResetWindow {
            get {
                return ResourceManager.GetString("MenuItemResetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuItemSave {
            get {
                return ResourceManager.GetString("MenuItemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuItemSettings {
            get {
                return ResourceManager.GetString("MenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started.
        /// </summary>
        public static string MenuItemStart {
            get {
                return ResourceManager.GetString("MenuItemStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table info.
        /// </summary>
        public static string MenuItemTableInfo {
            get {
                return ResourceManager.GetString("MenuItemTableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MenuItemTools {
            get {
                return ResourceManager.GetString("MenuItemTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        public static string NavHeaderDomain {
            get {
                return ResourceManager.GetString("NavHeaderDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string NavHeaderSetup {
            get {
                return ResourceManager.GetString("NavHeaderSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string NavHeaderTools {
            get {
                return ResourceManager.GetString("NavHeaderTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will add a new domain entry with default values. Once added, you can edit the values..
        /// </summary>
        public static string TextAddDomain {
            get {
                return ResourceManager.GetString("TextAddDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the size and position of the main window.
        /// </summary>
        public static string ToolTipResetMainWindow {
            get {
                return ResourceManager.GetString("ToolTipResetMainWindow", resourceCulture);
            }
        }
    }
}
